@ECHO OFF
CLS

SET GAME_RELEASE_DIR=Game
SET ENGINE_EXE_COMPILED=Engine.exe
SET GAME_EXE_DEBUG=Debug.exe
SET ENGINE_DEBUG_DIR=Engine\Debug

IF NOT EXIST "%GAME_RELEASE_DIR%" MKDIR "%GAME_RELEASE_DIR%"

ECHO Copying Debug Executable...
XCOPY "%ENGINE_DEBUG_DIR%\%ENGINE_EXE_COMPILED%" "%GAME_RELEASE_DIR%" /I /Y
IF EXIST "%GAME_RELEASE_DIR%\%GAME_EXE_DEBUG%" DEL "%GAME_RELEASE_DIR%\%GAME_EXE_DEBUG%"
REN "%GAME_RELEASE_DIR%\%ENGINE_EXE_COMPILED%" "%GAME_EXE_DEBUG%"

ECHO.
ECHO Done!

ECHO.
ECHO Running Debug Executable...
CD "%GAME_RELEASE_DIR%"
"%GAME_EXE_DEBUG%"
CD ..

ECHO.
ECHO Removing Debug Executable...
IF EXIST "%GAME_RELEASE_DIR%\%GAME_EXE_DEBUG%" DEL "%GAME_RELEASE_DIR%\%GAME_EXE_DEBUG%"

ECHO.
PAUSE
